[package]
name = "compiler"
version = "0.1.0"
authors = ["Colbyn Wadman <hello@colbyn.com>"]
edition = "2018"

[dependencies]
nom = "6.1.2"
num = "0.3"
# rand = {version = "0.8", features=['wasm32-unknown-unknown']}

